n1 = int(input("Digite o primeiro número:"))
n2 = int(input("Digite o segundo número:"))
som_ = (n1+n2)
sub_ = (n1-n2)
mult_ = (n1*n2)
div_ =(n1/n2)
print(f"A soma é {som_}")
print(f"A subtração é {sub_}")
print(f"A multiplicação é {mult_}")
print(f"A divisão é {div_}")